corner_detector:

  # Show map image if True
  show_image: False

  # Use contour approximation if true
  use_approximation: True

  # Contour approximation parameter
  approx_param: 0.005

  # Distance for contour point removal
  distance_threshold: 5

  # Determines the index of convex hull sorted by its area
  convex_hull_idx: 2  

corner_avoid:
  # Corners closer than this value to the global path will be avoided
  corner_distance_threshold: 0.7

  # Radius of avoiding area
  radius: 1.4

  # Step size for creating waypoints
  step_size: 30 # Degree

# global_plan topic name
global_plan_name: /move_base/NavfnROS/plan

# global_goal topic name with PoseStamped msg type
global_goal_name: /move_base/current_goal