corner_detector:
  # map_file directory
  # map_file: 

  # Show map image if True
  show_image: True

  # Use contour approximation if true
  use_approximation: True

  # Contour approximation parameter
  approx_param: 0.005

  # Distance for contour point removal
  distance_threshold: 5

  # Determines the index of convex hull sorted by its area
  convex_hull_idx: 2  
  
# global_plan topic name
global_plan_name: /move_base/NavfnROS/plan
  